# **Tutorial 5: Working with Data in Pandas**

## **Outline**

- Data Structures in Pandas
- Working with CSV Files
- Exploring and Inspecting Datasets
- Handling Missing Data

As we have learned, Python libraries can be used to extend the functionality of the programming language. Pandas is a popular library focused on data analysis that simplifies the process of loading, cleaning, analyzing and manipulating data.

## **Data Structures in Pandas**

Pandas provides two useful data object types: **Series** and **DataFrames**.

Series are one-dimensional arrays of data:

In [ ]:
import pandas as pd

mySeries = pd.Series([1,2,3,4,5])
print(mySeries)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In the above code, when we import the Pandas library, we created the alias `pd`. Using an alias allows us to shorten our code. This alias can technically be any string, but the unofficial standard for Pandas is "pd".

When we print out a Pandas Series, the left column represents the index value of each item in the Series, and the right column represents the value of the item.

By default, when creating a Series, the items are indexed numerically, but you can also provide your own indexes:

In [ ]:
import pandas as pd

mySeries = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
print(mySeries)

a    1
b    2
c    3
d    4
e    5
dtype: int64

You can also create a Series using a Python dictionary. In the below example the keys become the index, and the values become the data:

In [ ]:
import pandas as pd

data = {'apples': 5, 'oranges': 3, 'bananas': 7}

mySeries = pd.Series(data)
print(mySeries)

apples     5
oranges    3
bananas    7
dtype: int64

You can access items in a Series similar to how you access items in a list or dictionary:

In [ ]:
import pandas as pd

gradesSeries = pd.Series([55,78,87])
print(gradesSeries[1])

tempSeries = pd.Series([98.6, 98.9, 100.2], index = ['sample1','sample2','sample3'])
print(tempSeries['sample2'])

78
98.9

While Series can serve a useful purpose in Pandas, DataFrames which organize data in rows and columns, like a spreadsheet, are more commonly used.

DataFrames can be created in a variety of ways including from a dictionary:

In [ ]:
import pandas as pd


data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Toronto', 'Vancouver', 'Montreal']
}

df = pd.DataFrame(data)
print(df)

      Name  Age       City
0    Alice   25    Toronto
1      Bob   30  Vancouver
2  Charlie   35   Montreal

Columns of DataFrames can be accessed using the format below:

In [ ]:
# accessing one column of data from a DataFrame
print(df['Name'])

# accessing multiple columns of data from a DataFrame
print(df[['Name', 'Age']])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

DataFrame rows can be accessed by index name using the `.loc` property or by index position when using `.iloc`:

In [ ]:
import pandas as pd

students = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Grade': [82,99,72]
}

df = pd.DataFrame(students, index=['student1', 'student2', 'student3'])

print(df)
print("---------------------------------")
print(df.loc["student2"])
print("---------------------------------")
print(df.iloc[2])

             Name  Grade
student1    Alice     82
student2      Bob     99
student3  Charlie     72
---------------------------------
Name     Bob
Grade     99
Name: student2, dtype: object
---------------------------------
Name     Charlie
Grade         72
Name: student3, dtype: object

## **Working with CSV Files**

Thus far we have created DataFrames within Python code itself, but you can also build DataFrames from external files like CSV files:

In [ ]:
import pandas as pd

df = pd.read_csv('UNData.csv')
print(df)

     Country Name Country Code  Population 2010  Population 2020
0           Aruba          ABW           101838           108587
1     Afghanistan          AFG         28284089         39068979
2          Angola          AGO         23294825         33451132
3         Albania          ALB          2913021          2528480
4         Andorra          AND            80706            77380
..            ...          ...              ...              ...
212        Kosovo          XKX          1788743          1790151
213   Yemen, Rep.          YEM         26754387         36134863
214  South Africa          ZAF         52344051         60562381
215        Zambia          ZMB         13965594         19059395
216      Zimbabwe          ZWE         13356548         15526888

[217 rows x 4 columns]

In the above example our CSV file's first row contained the header values of our columns.

If your CSV file does not contain the labels of your columns, you can specify them in the `.read_csv()` function call:

In [ ]:
import pandas as pd

# Reading a file with no header and assigning names manually
df = pd.read_csv('noHeaders.csv', header=None, names=['City', 'Province', 'Population'])
df.head()

       City           Province  Population
0    Ottawa            Ontario      400000
1  Victoria   British Columbia      250000
2   Halifax        Nova Scotia      170000
3   Canmore            Alberta       27000

In addition to reading from CSV files, you can also write DataFrames to CSV files using the `.to_csv()` function:

In [ ]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Toronto', 'Vancouver', 'Montreal']
}

df = pd.DataFrame(data)

df.to_csv('employees.csv', index=False)

In the above example, we have set the `.to_csv()` index parameter to `False`, as we do not want to include the numeric index values as the first column of our CSV file.

## **Exploring and Inspecting Datasets**

Pandas offers several tools for interacting with and manipulating your data.

For instance, you can use the following techniques to quickly grasp the structure of a large dataset:

In [ ]:
import pandas as pd

df = pd.read_csv('UNData.csv')

# output the first 5 rows of your dataframe
df.head()

  Country Name Country Code  Population 2010  Population 2020
0        Aruba          ABW           101838           108587
1  Afghanistan          AFG         28284089         39068979
2       Angola          AGO         23294825         33451132
3      Albania          ALB          2913021          2528480
4      Andorra          AND            80706            77380

In [ ]:
# output the last 5 rows of your dataframe
df.tail()

     Country Name Country Code  Population 2010  Population 2020
212        Kosovo          XKX          1788743          1790151
213   Yemen, Rep.          YEM         26754387         36134863
214  South Africa          ZAF         52344051         60562381
215        Zambia          ZMB         13965594         19059395
216      Zimbabwe          ZWE         13356548         15526888

When working in Jupyter Notebooks, you do not need to wrap `.head()` (or similar methods) in a `print()` statement.

Simply placing the command on the last line of a code cell will automatically display the data as a nicely formatted table. Note that Jupyter only provides this "pretty" formatting for the very last item in a cell, so if you have multiple `.head()` calls in one block, only the final one will be shown.

Here are a few more ways you can use Pandas to get more information on your dataset:

In [ ]:
# output the dimensions of your dataframe
df.shape

(217, 4)

In [ ]:
# output the column names of your dataframe
df.columns

Index(['Country Name', 'Country Code', 'Population 2010', 'Population 2020'], dtype='object')

In [ ]:
# output the data types and other info of your dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 217 entries, 0 to 216
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country Name     217 non-null    object
 1   Country Code     217 non-null    object
 2   Population 2010  217 non-null    int64
 3   Population 2020  217 non-null    int64
dtypes: int64(2), object(2)
memory usage: 6.9+ KB

Pandas also allows you to filter your DataFrame based on a column value as seen below:

In [ ]:
df[df['Population 2020'] > 200000000]

      Country Name Country Code  Population 2010  Population 2020
26          Brazil          BRA        193701929        208660842
36           China          CHN       1337705000       1411100000
87       Indonesia          IDN        246305322        274814866
89           India          IND       1243481564       1402617695
142        Nigeria          NGA        166642886        213996181
150       Pakistan          PAK        199239047        235001746
203  United States          USA        309378227        331577720

We can also add new column:

In [ ]:
df['10 Year Change'] = df['Population 2020'] - df['Population 2010']
df.head()

  Country Name Country Code  Population 2010  Population 2020  10 Year Change
0        Aruba          ABW           101838           108587            6749
1  Afghanistan          AFG         28284089         39068979        10784890
2       Angola          AGO         23294825         33451132        10156307
3      Albania          ALB          2913021          2528480         -384541
4      Andorra          AND            80706            77380           -3326

In the above example, we added a new column called `10 Year Change`, which is created by *calculating the difference between the 2020 and 2010* population columns.

This calculation is done for every row in our DataFrame, and the result is placed in our new column.

You can also easily delete a column:

In [ ]:
df.drop(columns=['Country Code'], inplace=True)
df.head()

  Country Name  Population 2010  Population 2020  10 Year Change
0        Aruba           101838           108587            6749
1  Afghanistan         28284089         39068979        10784890
2       Angola         23294825         33451132        10156307
3      Albania          2913021          2528480         -384541
4      Andorra            80706            77380           -3326

In the above example, we set the `inplace` value to True, so we can make direct changes on our DataFrame.

If you want to keep your original DataFrame, you can leave out this value or set it to False, and then create a new DataFrame as seen below:

In [ ]:
newDf = df.drop(columns=['10 Year Change'])
print("New DataFrame:")
print(newDf.head())
print("Original DataFrame")
print(df.head())

New DataFrame:
  Country Name  Population 2010  Population 2020
0        Aruba           101838           108587
1  Afghanistan         28284089         39068979
2       Angola         23294825         33451132
3      Albania          2913021          2528480
4      Andorra            80706            77380
Original DataFrame
  Country Name  Population 2010  Population 2020  10 Year Change
0        Aruba           101838           108587            6749
1  Afghanistan         28284089         39068979        10784890
2       Angola         23294825         33451132        10156307
3      Albania          2913021          2528480         -384541
4      Andorra            80706            77380           -3326

Pandas can also provide simple statistics on your dataset as seen below:

In [ ]:
print(df['Population 2020'].mean())
print(df['Population 2020'].min())
print(df['Population 2020'].max())

36088316.13364055
10399
1411100000

Pandas also allows you to sort your DataFrame by column:

In [ ]:
df.sort_values(by='Population 2020',inplace=True)
df.head()

,Country Name,Population 2010,Population 2020,10 Year Change
198,Tuvalu,10614,10399,-215
147,Nauru,10043,11643,1600
154,Palau,18396,17792,-604
119,St. Martin (French part),36856,31786,-5070
174,San Marino,33270,34770,1500

Sorting is done in ascending order by default, but that can be switched to descending order:

In [ ]:
df.sort_values(by='Population 2020',ascending=False, inplace=True)
df.head()

      Country Name  Population 2010  Population 2020  10 Year Change
36           China       1337705000       1411100000        73395000
89           India       1243481564       1402617695       159136131
203  United States        309378227        331577720        22199493
87       Indonesia        246305322        274814866        28509544
150       Pakistan        199239047        235001746        35762699

## **Handling Missing Data**

Often when working with data, our datasets will contain missing values. Pandas has several built-in tools that can help us clean and manipulate this data.

To see this in action, let's load a new dataset from a CSV, which contains grocery store inventory data:

In [ ]:
import pandas as pd

df = pd.read_csv('groceries.csv')
df.head()

              item_name  item_sale_price  item_wholesale_price  item_quantity
0     Honey Crisp Apple            10.84                  9.77           36.0
1  Sharp Cheddar Cheese              NaN                 13.30           25.0
2      Cavendish Banana              NaN                  4.00           14.0
3                   NaN            15.02                 10.31           12.0
4       Sourdough Bread            10.08                  9.06           12.0

Taking a closer look at this DataFrame, you will see several rows with missing data. When a CSV file with missing data is read into Pandas by default those cells are given the value of `NaN`, which stands for **“not a number”**.

A simple way to handle missing data, is to remove any row that contains at least one missing value:

In [ ]:
cleanDf = df.dropna()
cleanDf.head()

,item_name,item_sale_price,item_wholesale_price,item_quantity
0,Honey Crisp Apple,10.84,9.77,36.0
4,Sourdough Bread,10.08,9.06,12.0
5,Large Brown Eggs,4.78,3.67,4.0
6,Frosted Flakes Cereal,11.98,8.64,90.0
7,Boneless Chicken Breast,9.98,8.40,76.0

The `.dropna()` function can also be used to remove rows that are only missing values in a specific column:

In [ ]:
cleanDf = df.dropna(subset=['item_name'])
cleanDf.head()

              item_name  item_sale_price  item_wholesale_price  item_quantity
0     Honey Crisp Apple            10.84                  9.77           36.0
1  Sharp Cheddar Cheese              NaN                 13.30           25.0
2      Cavendish Banana              NaN                  4.00           14.0
4       Sourdough Bread            10.08                  9.06           12.0
5      Large Brown Eggs             4.78                  3.67            4.0

Pandas also allows you to replace missing values with a specific value using the `.fillna()` function :

In [ ]:
df["item_name"] = df["item_name"].fillna("Unknown Item Name")
df.head()

              item_name  item_sale_price  item_wholesale_price  item_quantity
0     Honey Crisp Apple            10.84                  9.77           36.0
1  Sharp Cheddar Cheese              NaN                 13.30           25.0
2      Cavendish Banana              NaN                  4.00           14.0
3     Unknown Item Name            15.02                 10.31           12.0
4       Sourdough Bread            10.08                  9.06           12.0

This replacement value can also be calculated from a value in another column from the same row.

In the code below, we set any missing sale item price cells to a value of 10% higher than the wholesale price:

In [ ]:
df["item_sale_price"] = df["item_sale_price"].fillna(df["item_wholesale_price"]*1.10)
df.head()

              item_name  item_sale_price  item_wholesale_price  item_quantity
0     Honey Crisp Apple            10.84                  9.77           36.0
1  Sharp Cheddar Cheese            14.63                 13.30           25.0
2      Cavendish Banana             4.40                  4.00           14.0
3     Unknown Item Name            15.02                 10.31           12.0
4       Sourdough Bread            10.08                  9.06           12.0

Pandas allows you to group data together to get summary statistics on a larger dataset. This follows a **split-apply-combine** logic:

1.   **Split** the data into groups based on some criteria
2.   **Apply** a function to each of these groups
3.   **Combine** the results into a new data structure

Pandas has several built-in functions that you can apply to grouped data including `.mean()`, `.sum()` and `.count()`.

Below is an example of how use Pandas to find the total sales for each branch contained in a DataFrame:

In [ ]:
import pandas as pd

data = {
    'Branch': ['East', 'West', 'East', 'North', 'West', 'East'],
    'Sales': [100, 200, 150, 300, 250, 50],
    'Region': ['A', 'B', 'A', 'A', 'B', 'A']
}

df = pd.DataFrame(data)

# Group by Branch and sum the Sales
branch_totals = df.groupby('Branch')['Sales'].sum()

print(branch_totals)

Branch
East     300
North    300
West     450
Name: Sales, dtype: int64

You can also apply multiple functions at one time:

In [ ]:
stats = df.groupby('Branch')['Sales'].agg(['mean', 'max', 'count'])
stats

         mean  max  count
Branch
East    100.0  150      3
North   300.0  300      1
West    225.0  250      2

Depending on the amount of columns within your results, your split-apply-combine action will either return as a Pandas Series (as in our first example) or a DataFrame (as in our second example).

You can interact with the results in the same way as you would any Series or Dataframe.